/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\vuepress-blog-demo\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-324c2506",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-324c2506").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-56ad773e",
    path: "/%E5%8D%95%E7%9B%AE%E5%BD%95/01.%E6%96%87%E7%AB%A0%E4%B8%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56ad773e").then(next)
    },
  },
  {
    path: "/单目录/01.文章一.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/01.%E6%96%87%E7%AB%A0%E4%B8%80.html"
  },
  {
    path: "/单目录/01.文章一.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/01.%E6%96%87%E7%AB%A0%E4%B8%80.html"
  },
  {
    name: "v-0ddc21f4",
    path: "/%E5%8D%95%E7%9B%AE%E5%BD%95/02.%E6%96%87%E7%AB%A0%E4%BA%8C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ddc21f4").then(next)
    },
  },
  {
    path: "/单目录/02.文章二.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/02.%E6%96%87%E7%AB%A0%E4%BA%8C.html"
  },
  {
    path: "/单目录/02.文章二.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/02.%E6%96%87%E7%AB%A0%E4%BA%8C.html"
  },
  {
    name: "v-64bbe628",
    path: "/%E5%8D%95%E7%9B%AE%E5%BD%95/03.%E6%96%87%E7%AB%A0%E4%B8%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64bbe628").then(next)
    },
  },
  {
    path: "/单目录/03.文章三.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/03.%E6%96%87%E7%AB%A0%E4%B8%89.html"
  },
  {
    path: "/单目录/03.文章三.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/03.%E6%96%87%E7%AB%A0%E4%B8%89.html"
  },
  {
    name: "v-664d373e",
    path: "/%E5%8D%95%E7%9B%AE%E5%BD%95/04.%E6%96%87%E7%AB%A0%E5%9B%9B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-664d373e").then(next)
    },
  },
  {
    path: "/单目录/04.文章四.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/04.%E6%96%87%E7%AB%A0%E5%9B%9B.html"
  },
  {
    path: "/单目录/04.文章四.html",
    redirect: "/%E5%8D%95%E7%9B%AE%E5%BD%95/04.%E6%96%87%E7%AB%A0%E5%9B%9B.html"
  },
  {
    name: "v-546df64f",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/01.%E7%AB%A0%E8%8A%821-1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-546df64f").then(next)
    },
  },
  {
    path: "/多目录/01.章节1/01.章节1-1.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/01.%E7%AB%A0%E8%8A%821-1.html"
  },
  {
    path: "/多目录/01.章节1/01.章节1-1.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/01.%E7%AB%A0%E8%8A%821-1.html"
  },
  {
    name: "v-75ea66e2",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/02.%E7%AB%A0%E8%8A%821-2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75ea66e2").then(next)
    },
  },
  {
    path: "/多目录/01.章节1/02.章节1-2.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/02.%E7%AB%A0%E8%8A%821-2.html"
  },
  {
    path: "/多目录/01.章节1/02.章节1-2.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/02.%E7%AB%A0%E8%8A%821-2.html"
  },
  {
    name: "v-1a399a2f",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/01.%E7%AB%A0%E8%8A%822-1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a399a2f").then(next)
    },
  },
  {
    path: "/多目录/02.章节2/01.章节2-1.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/01.%E7%AB%A0%E8%8A%822-1.html"
  },
  {
    path: "/多目录/02.章节2/01.章节2-1.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/01.%E7%AB%A0%E8%8A%822-1.html"
  },
  {
    name: "v-ea531f22",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/02.%E7%AB%A0%E8%8A%822-2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea531f22").then(next)
    },
  },
  {
    path: "/多目录/02.章节2/02.章节2-2.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/02.%E7%AB%A0%E8%8A%822-2.html"
  },
  {
    path: "/多目录/02.章节2/02.章节2-2.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/02.%E7%AB%A0%E8%8A%822-2.html"
  },
  {
    name: "v-091972a2",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/03.%E7%AB%A0%E8%8A%822-3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-091972a2").then(next)
    },
  },
  {
    path: "/多目录/02.章节2/03.章节2-3.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/03.%E7%AB%A0%E8%8A%822-3.html"
  },
  {
    path: "/多目录/02.章节2/03.章节2-3.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/03.%E7%AB%A0%E8%8A%822-3.html"
  },
  {
    name: "v-6c101cef",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/04.%E7%AB%A0%E8%8A%822-4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c101cef").then(next)
    },
  },
  {
    path: "/多目录/02.章节2/04.章节2-4.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/04.%E7%AB%A0%E8%8A%822-4.html"
  },
  {
    path: "/多目录/02.章节2/04.章节2-4.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/04.%E7%AB%A0%E8%8A%822-4.html"
  },
  {
    name: "v-3ff583e2",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/01.%E7%AB%A0%E8%8A%823-1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ff583e2").then(next)
    },
  },
  {
    path: "/多目录/03.章节3/01.章节3-1.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/01.%E7%AB%A0%E8%8A%823-1.html"
  },
  {
    path: "/多目录/03.章节3/01.章节3-1.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/01.%E7%AB%A0%E8%8A%823-1.html"
  },
  {
    name: "v-50a2144f",
    path: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/02.%E7%AB%A0%E8%8A%823-2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50a2144f").then(next)
    },
  },
  {
    path: "/多目录/03.章节3/02.章节3-2.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/02.%E7%AB%A0%E8%8A%823-2.html"
  },
  {
    path: "/多目录/03.章节3/02.章节3-2.html",
    redirect: "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/02.%E7%AB%A0%E8%8A%823-2.html"
  },
  {
    name: "v-6acabfc4",
    path: "/%E6%8C%87%E5%8D%97/01.%E4%BB%8B%E7%BB%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6acabfc4").then(next)
    },
  },
  {
    path: "/指南/01.介绍.html",
    redirect: "/%E6%8C%87%E5%8D%97/01.%E4%BB%8B%E7%BB%8D.html"
  },
  {
    path: "/指南/01.介绍.html",
    redirect: "/%E6%8C%87%E5%8D%97/01.%E4%BB%8B%E7%BB%8D.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-b53ec9e8",
    path: "/tag/webpack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b53ec9e8").then(next)
    },
    meta: {"pid":"tags","id":"webpack"}
  },
  {
    path: "/tag/webpack/index.html",
    redirect: "/tag/webpack/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]