/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "vuepress-reco",
  "description": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "https://cdn.jsdelivr.net/gh/qqlcx5/figure-bed@v1.0.0/image/polar_bear.jpg"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ],
    [
      "script",
      {
        "async": "async",
        "src": "https://hm.baidu.com/hm.js?27c61fbfe7c9201c97b53d619459c89d"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "前端有道",
        "tagline": "A magical Wechat account",
        "heroImage": "https://cdn.jsdelivr.net/gh/qqlcx5/figure-bed@v1.0.0/image/qc-play.png",
        "heroImageStyle": {
          "maxWidth": "650px",
          "width": "100%",
          "display": "block",
          "margin": "1rem auto 1rem"
        },
        "isShowTitleInHome": false,
        "actionText": "开始迁移 →",
        "actionLink": "/指南/01.介绍",
        "features": [
          {
            "title": "前端有道交流群",
            "details": "交流技术和解决工作上困难。"
          },
          {
            "title": "汇聚众多的前端资源",
            "details": "正所谓工欲善其事，必先利其器"
          },
          {
            "title": "分享技术文章",
            "details": "分享学到的知识，分享生活的感悟"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-324c2506",
      "path": "/",
      "lastUpdated": "2019-05-12 14:58",
      "lastUpdatedTimestamp": 1557644301000
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%8D%95%E7%9B%AE%E5%BD%95/01.%E6%96%87%E7%AB%A0%E4%B8%80.html",
      "relativePath": "单目录/01.文章一.md",
      "key": "v-56ad773e",
      "path": "/%E5%8D%95%E7%9B%AE%E5%BD%95/01.%E6%96%87%E7%AB%A0%E4%B8%80.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%8D%95%E7%9B%AE%E5%BD%95/02.%E6%96%87%E7%AB%A0%E4%BA%8C.html",
      "relativePath": "单目录/02.文章二.md",
      "key": "v-0ddc21f4",
      "path": "/%E5%8D%95%E7%9B%AE%E5%BD%95/02.%E6%96%87%E7%AB%A0%E4%BA%8C.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%8D%95%E7%9B%AE%E5%BD%95/03.%E6%96%87%E7%AB%A0%E4%B8%89.html",
      "relativePath": "单目录/03.文章三.md",
      "key": "v-64bbe628",
      "path": "/%E5%8D%95%E7%9B%AE%E5%BD%95/03.%E6%96%87%E7%AB%A0%E4%B8%89.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%8D%95%E7%9B%AE%E5%BD%95/04.%E6%96%87%E7%AB%A0%E5%9B%9B.html",
      "relativePath": "单目录/04.文章四.md",
      "key": "v-664d373e",
      "path": "/%E5%8D%95%E7%9B%AE%E5%BD%95/04.%E6%96%87%E7%AB%A0%E5%9B%9B.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/01.%E7%AB%A0%E8%8A%821-1.html",
      "relativePath": "多目录/01.章节1/01.章节1-1.md",
      "key": "v-546df64f",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/01.%E7%AB%A0%E8%8A%821-1.html",
      "headers": [
        {
          "level": 2,
          "title": "h2章节1-1",
          "slug": "h2章节1-1"
        },
        {
          "level": 3,
          "title": "h3章节1-1",
          "slug": "h3章节1-1"
        }
      ]
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/02.%E7%AB%A0%E8%8A%821-2.html",
      "relativePath": "多目录/01.章节1/02.章节1-2.md",
      "key": "v-75ea66e2",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/01.%E7%AB%A0%E8%8A%821/02.%E7%AB%A0%E8%8A%821-2.html",
      "headers": [
        {
          "level": 2,
          "title": "h2章节1-2",
          "slug": "h2章节1-2"
        },
        {
          "level": 3,
          "title": "h3章节1-2",
          "slug": "h3章节1-2"
        }
      ]
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/01.%E7%AB%A0%E8%8A%822-1.html",
      "relativePath": "多目录/02.章节2/01.章节2-1.md",
      "key": "v-1a399a2f",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/01.%E7%AB%A0%E8%8A%822-1.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/02.%E7%AB%A0%E8%8A%822-2.html",
      "relativePath": "多目录/02.章节2/02.章节2-2.md",
      "key": "v-ea531f22",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/02.%E7%AB%A0%E8%8A%822-2.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/03.%E7%AB%A0%E8%8A%822-3.html",
      "relativePath": "多目录/02.章节2/03.章节2-3.md",
      "key": "v-091972a2",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/03.%E7%AB%A0%E8%8A%822-3.html"
    },
    {
      "title": "【vue】跨域解决方案之proxyTable",
      "frontmatter": {
        "title": "【vue】跨域解决方案之proxyTable",
        "date": "2017-12-28T00:00:00.000Z",
        "tags": [
          "vue",
          "webpack"
        ]
      },
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/04.%E7%AB%A0%E8%8A%822-4.html",
      "relativePath": "多目录/02.章节2/04.章节2-4.md",
      "key": "v-6c101cef",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/02.%E7%AB%A0%E8%8A%822/04.%E7%AB%A0%E8%8A%822-4.html"
    },
    {
      "title": "章节3-1",
      "frontmatter": {},
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/01.%E7%AB%A0%E8%8A%823-1.html",
      "relativePath": "多目录/03.章节3/01.章节3-1.md",
      "key": "v-3ff583e2",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/01.%E7%AB%A0%E8%8A%823-1.html",
      "headers": [
        {
          "level": 2,
          "title": "h2章节3-1",
          "slug": "h2章节3-1"
        },
        {
          "level": 3,
          "title": "h3章节3-1",
          "slug": "h3章节3-1"
        }
      ]
    },
    {
      "title": "章节3-2",
      "frontmatter": {},
      "regularPath": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/02.%E7%AB%A0%E8%8A%823-2.html",
      "relativePath": "多目录/03.章节3/02.章节3-2.md",
      "key": "v-50a2144f",
      "path": "/%E5%A4%9A%E7%9B%AE%E5%BD%95/03.%E7%AB%A0%E8%8A%823/02.%E7%AB%A0%E8%8A%823-2.html",
      "headers": [
        {
          "level": 2,
          "title": "h2章节3-2",
          "slug": "h2章节3-2"
        },
        {
          "level": 3,
          "title": "h3章节3-2",
          "slug": "h3章节3-2"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/%E6%8C%87%E5%8D%97/01.%E4%BB%8B%E7%BB%8D.html",
      "relativePath": "指南/01.介绍.md",
      "key": "v-6acabfc4",
      "path": "/%E6%8C%87%E5%8D%97/01.%E4%BB%8B%E7%BB%8D.html",
      "headers": [
        {
          "level": 2,
          "title": "它是如何工作的？",
          "slug": "它是如何工作的"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue Tags"
      },
      "regularPath": "/tag/vue/",
      "key": "v-322a45da",
      "path": "/tag/vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "webpack Tags"
      },
      "regularPath": "/tag/webpack/",
      "key": "v-b53ec9e8",
      "path": "/tag/webpack/"
    }
  ],
  "themeConfig": {
    "editLinks": true,
    "smoothScroll": true,
    "lastUpdated": "最后更新时间",
    "nav": [
      {
        "text": "指南",
        "link": "/指南/01.介绍"
      },
      {
        "text": "单目录",
        "link": "/单目录/01.文章一"
      },
      {
        "text": "多目录",
        "link": "/多目录/01.章节1/01.章节1-1"
      }
    ],
    "sidebar": {
      "/指南/": [
        {
          "title": "基础",
          "collapsable": false,
          "children": [
            [
              "01.介绍",
              "介绍"
            ]
          ]
        }
      ],
      "/单目录/": [
        {
          "title": "单目录标题",
          "collapsable": false,
          "children": [
            [
              "01.文章一",
              "文章一"
            ],
            [
              "02.文章二",
              "文章二"
            ],
            [
              "03.文章三",
              "文章三"
            ],
            [
              "04.文章四",
              "文章四"
            ]
          ]
        }
      ],
      "/多目录/": [
        {
          "title": "章节1",
          "collapsable": false,
          "children": [
            [
              "01.章节1/01.章节1-1",
              "章节1-1"
            ],
            [
              "01.章节1/02.章节1-2",
              "章节1-2"
            ]
          ]
        },
        {
          "title": "章节2",
          "collapsable": false,
          "children": [
            [
              "02.章节2/01.章节2-1",
              "章节2-1"
            ],
            [
              "02.章节2/02.章节2-2",
              "章节2-2"
            ],
            [
              "02.章节2/03.章节2-3",
              "章节2-3"
            ],
            [
              "02.章节2/04.章节2-4",
              "章节2-4"
            ]
          ]
        },
        {
          "title": "章节3",
          "collapsable": false,
          "children": [
            [
              "03.章节3/01.章节3-1",
              "章节3-1"
            ],
            [
              "03.章节3/02.章节3-2",
              "章节3-2"
            ]
          ]
        }
      ]
    }
  }
}