/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-56ad773e",
        "v-0ddc21f4",
        "v-64bbe628",
        "v-664d373e",
        "v-546df64f",
        "v-75ea66e2",
        "v-1a399a2f",
        "v-ea531f22",
        "v-091972a2",
        "v-6c101cef"
      ]
    },
    "webpack": {
      "key": "webpack",
      "scope": "tags",
      "path": "/tag/webpack/",
      "pageKeys": [
        "v-56ad773e",
        "v-0ddc21f4",
        "v-64bbe628",
        "v-664d373e",
        "v-546df64f",
        "v-75ea66e2",
        "v-1a399a2f",
        "v-ea531f22",
        "v-091972a2",
        "v-6c101cef"
      ]
    }
  },
  "categories": {},
  "timeline": {}
}